# Generated by Django 5.0.4 on 2024-07-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Boleta')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.BigIntegerField(verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Marca')),
                ('nombreMarca', models.CharField(blank=True, max_length=50, verbose_name='Nombre Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoId', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('nombreMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.marca', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('id_boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.producto', verbose_name='Producto'),
        ),
    ]
